### ISSUE TITLE
Disappearing platforms show wrong sprite in 'in the swing'.

### ISSUE THREAD

**Issue by FolkertVanVerseveld** [ErikaRedmark/monkey-shines-java-port#94]
After the disappearing platforms should vanish, it just shows a weird tile.
See the attachment for more details.
![swing_platforms](https://cloud.githubusercontent.com/assets/5989565/11562957/7152f24c-99d1-11e5-9d2d-d00b6af3bc2a.png)

**Comment by ErikaRedmark** [comment]
It has been a VERY long time since I even looked at this project; with the knowledge I have now, when I finish my current project I really want to rip out the entire graphics system and replace it with a well-maintained library, like Slick2D. At the moment I am at a loss why this is occurring.

**Comment by ErikaRedmark** [comment]
I'm currently rewriting the rendering to use Slick2D as a base instead of AWT. I am hoping one of the side effects will be removing these visual artifacts.

**Comment by ErikaRedmark** [comment]
The latest release now uses Slick2D. I have been unable to replicate this myself, but I am really hoping this visual glitch that was present in the old engine (since by all accounts the data said the platform should be showing its last frame just like any other platform, especially weird that the tile shown wasn't even part of the spritesheet actively drawn by the collapsing tile) would not be in this new one.

I will close this bug for now, but if you get this with the new release that uses lwjgl, please feel free to reopen this again.
